time: 2017-04-11 09:00:50.783341Z
tags: worker-0
test: unittest2.loader._FailedTest.tempest.test_discover.test_discover
time: 2017-04-11 09:00:50.783486Z
failure: unittest2.loader._FailedTest.tempest.test_discover.test_discover [ multipart
Content-Type: text/x-traceback;charset=utf8,language=python
traceback
2CD
Traceback (most recent call last):
ImportError: Failed to import test module: tempest.test_discover.test_discover
Traceback (most recent call last):
  File "/root/tempest/.venv/lib/python2.7/site-packages/unittest2/loader.py", line 456, in _find_test_path
    module = self._get_module_from_name(name)
  File "/root/tempest/.venv/lib/python2.7/site-packages/unittest2/loader.py", line 395, in _get_module_from_name
    __import__(name)
  File "tempest/test_discover/test_discover.py", line 18, in <module>
    from tempest.test_discover import plugins
  File "tempest/test_discover/plugins.py", line 20, in <module>
    from tempest_lib.common.utils import misc
ImportError: No module named tempest_lib.common.utils

0
]
tags: -worker-0
